build: implement support for deleting (remote) modules
Add build system options for cleaning up kernel module and symlinks to
kernel modules.  This is needed when removing some modules, else
depmod can get confused.

The new make target is called "clean_remote" usage:
 make clean_remote HOST=192.168.122.49

For localhost usage, the setup_prototype_devel_env.sh can be
called with the long option --delete (which is what happens
on the remote host).

This will delete files/symlinks under: /lib/modules/`uname -r`/kernel/extra
and find all *.ko files and delete those.

Signed-off-by: Jesper Dangaard Brouer <brouer@redhat.com>

diff --git a/kernel/Makefile b/kernel/Makefile
--- a/kernel/Makefile
+++ b/kernel/Makefile
@@ -40,6 +40,15 @@ push_remote: modules
 	fi
 	scripts/push_remote.sh $(HOST)
 
+clean_remote:
+	@if [ -z $(HOST) ]; then \
+		echo -e "\n ***ERROR***: need remote \"HOST\" variable, use:"; \
+		echo -e "  make clean_remote HOST=192.168.122.49\n"; \
+		exit 2; \
+	fi
+	scripts/push_remote.sh --delete $(HOST)
+
+
 clean:
 	$(MAKE) -C $(kbuilddir) M=$$PWD KDIR=$$PWD clean
 	@rm -f *~
